### ISSUE TITLE
why using "array" as an input for iteratorFn()

### ISSUE THREAD

**Issue by xleili** [rxaviers/async-pool#27]
https://github.com/rxaviers/async-pool/blob/master/lib/es6.js line:26
const p = Promise.resolve().then(() => iteratorFn(item, array));

I was not quite understand why using array as an input parameter for iteratorFn();
In my opinion, we need to transport item to the iteratorFn which will actually be execute. 
where is the usage of “array”. can someone help?

**Comment by rxaviers** [comment]
Actually, the parameter should be any [iterable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterable_protocol), array being one of them.

Do you want to submit a PR with appropriate changes? I am open to drop `yaassertion` completely and release such change in a new major version.

**Comment by QAnders** [comment]
Not sure if you are asking about the function of the array (iterator) or asking for an enhancement but if it is the former the array
is the inputs to the function per iteration.

For example, we use it to upload files to a SFTP server and we can use a maximum of 5 concurrent connections but we often have hundreds of files.

First we get a list of files to be uploaded from an AWS S3 bucket and we put the file names into an array.
Next we want to upload the files, five at a time, to the SFTP server:
```
const files = await getFileListFromS3();
// call uploadFile() for each file with a maximum of five concurrent iterations
await asyncPool(5, files, uploadFile);
```

What would be nice though is to be able to set the number iterations instead of an array controlling the number. E.g. if I don't have any input to the function but I know the number of times I'd like to call it I could give a number as input instead of an array...

**Comment by xleili** [comment]
> Actually, the parameter should be any [iterable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterable_protocol), array being one of them.
> 
> Do you want to submit a PR with appropriate changes? I am open to drop `yaassertion` completely and release such change in a new major version.

thank you for your answer. I was new to js and I got confused when asked these question. But now I'm good.

**Comment by xleili** [comment]
> Not sure if you are asking about the function of the array (iterator) or asking for an enhancement but if it is the former the array is the inputs to the function per iteration.
> 
> For example, we use it to upload files to a SFTP server and we can use a maximum of 5 concurrent connections but we often have hundreds of files.
> 
> First we get a list of files to be uploaded from an AWS S3 bucket and we put the file names into an array. Next we want to upload the files, five at a time, to the SFTP server:
> 
> ```
> const files = await getFileListFromS3();
> // call uploadFile() for each file with a maximum of five concurrent iterations
> await asyncPool(5, files, uploadFile);
> ```
> 
> What would be nice though is to be able to set the number iterations instead of an array controlling the number. E.g. if I don't have any input to the function but I know the number of times I'd like to call it I could give a number as input instead of an array...

thank you for you explanation, It helps me understand more.
