### ISSUE TITLE
Feature: guarantee order of results

### ISSUE THREAD

**Issue by AlbertoMontalesi** [rxaviers/async-pool#41]
The way we used to use this library was something along these lines:

```
// fetch a list of rows from the database;
const rawRows = await sqlQuery;

// construct the complete objects from those rows
const rows = await asyncPool(10,rawRows, async (row) => {const completeRow = await doSomething(row); return completeRow})`
```

The problem with V2 is that since now each result returns as soon as it completes, the array `rows` in the previous example is not guaranteed to be in the same order as `rawRows`, it will all depend on how fast the callbacks run.

The following is just a simple example to see it in action

```
console.log('start pool ---------------');
	const results = [];
	for await (const result of asyncPool(10, [1, 2, 3, 4, 5], async (val) => {
		await new Promise((res) => setTimeout(res, 1000 / val));
		console.log(val);
		return val;
	})) {
		results.push(result);
	}
	console.log('end pool --------- ');
```

which results in

```
start pool ---------------
5
4
3
2
1
end pool --------- 
```

I see that V1 was calling promise.all whereas V2 uses promise.race even if the pool is larger than the list of arrays.

Would it be possible for this library to preserve the order of the items of the array?

**Comment by jpike88** [comment]
@rxaviers Ive been using the lib the entire time under the impression that order is preserved. Naive for me to do so, but it's an easy mistake to make. Are you interested in making a preserveOrder flag for how things work out, if so do you have a suggestion for how you feel that's best done?

**Comment by rxaviers** [comment]
A note for everyone that's already using v1: you don't need to migrate to v2 if you don't need to, because the v1 branch is likely to be maintained too.

The v2 API is different than the v1 API (as the major bump implies).
- v2 provides finer control: thanks to [async iteration](https://github.com/tc39/proposal-async-iteration), it lets each result be returned as soon as it completes
- it's possible to get a v1 API (from the v2 lib) by using the wrapper found on https://github.com/rxaviers/async-pool#migrating-from-1x --- though it needs an update, thank you @AlbertoMontalesi [1]

1: I believe the function below would work. Do you want to test it and let us know? It would also be helpful to update README.md with either it or a better one? Thanks

```js
async function asyncPoolAll(concurrency, iterable, iteratorFn) {
  const results = [];
  const iterableWithIndex = Object.entries({ ...iterable });
  for await (const [i, result] of asyncPool(concurrency, iterableWithIndex, iteratorFn)) {
    result[i] = result;
  }
  return results;
}
```

**Comment by rxaviers** [comment]
I'm closing per last comment. We can reopen if there's an action required. Thanks
