### ISSUE TITLE
README.md usage issue

### ISSUE THREAD

**Issue by duarbdhks** [rxaviers/async-pool#45]
When I checked how to use it in README, it said to do the following when importing.
````javascript
import asyncPool from "tiny-async-pool";
````

However, when it was actually imported and used, it was used only as follows.
````javascript
import * as asyncPool from "tiny-async-pool";
````

**Comment by rafaelxavier-medicalbox** [comment]
Please, are you using any transpilers (such as babel or typescript)? Or are you using it directly from node.js module (e.g., an .mjs file)?

PS: Maybe there are two updates that need to happen in this repo
1. Update https://nodejs.org/api/packages.html#type "module"
2. Update Use ES6 `export` here https://github.com/rxaviers/async-pool/blob/master/lib/es9.js#L25 instead of `module.exports`
3. Figure out backward compatibility with existing export

**Comment by rxaviers** [comment]
Please, are you using any transpilers (such as babel or typescript)? Or are you using it directly from node.js module (e.g., an .mjs file)?

PS: Maybe there are two updates that need to happen in this repo
1. Update https://nodejs.org/api/packages.html#type "module"
2. Update Use ES6 `export` here https://github.com/rxaviers/async-pool/blob/master/lib/es9.js#L25 instead of `module.exports`

Then, figure out backward compatibility with existing export

**Comment by duarbdhks** [comment]
Thank you for checking. I used `typescript` and module was set to `commonjs`. So I used it in the form below.
````typescript
import * as asyncPool from "tiny-async-pool"
````

The issue may be closed.
